GROUND_STATION_LIST = "/api/ground-stations"
GROUND_STATION_CREATE = "/api/ground-stations"
GROUND_STATION_UPDATE = "/api/ground-stations/{ground_station_id:uuid}"
GROUND_STATION_DELETE = "/api/ground-stations/{ground_station_id:uuid}"
GROUND_STATION_DETAILS = "/api/ground-stations/{ground_station_id:uuid}"
