ORBIT_LIST = "/api/orbits"
ORBIT_CREATE = "/api/orbits"
ORBIT_UPDATE = "/api/orbits/{ground_station_id:uuid}"
ORBIT_DELETE = "/api/orbits/{ground_station_id:uuid}"
ORBIT_DETAILS = "/api/orbits/{ground_station_id:uuid}"
