DATA_STATUS_LIST = "/api/data-status"
DATA_STATUS_UPDATE = "/api/data-status/{data_id:int}"
DATA_STATUS_DELETE = "/api/data-status/{data_id:int}"
DATA_STATUS_DETAILS = "/api/data-status/{data_id:int}"
DATA_UPDATE_CREATE = "/api/data-update/{data_id:int}"