DYNAMICS_LIST = "/api/dynamics"
DYNAMICS_CREATE = "/api/dynamics"
DYNAMICS_UPDATE = "/api/dynamics/{dynamics_id:uuid}"
DYNAMICS_DELETE = "/api/dynamics/{dynamics_id:uuid}"
DYNAMICS_DETAILS = "/api/dynamics/{dynamics_id:uuid}"
