PROPAGATION_LIST = "/api/propagation"
PROPAGATION_REQUEST = "/api/propagation"
# TAG_UPDATE = "/api/dynamics/{dynamics_id:uuid}"
# TAG_DELETE = "/api/dynamics/{dynamics:uuid}"
# TAG_DETAILS = "/api/dynamics/{dynamics:uuid}"
